/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CartItemService } from "../cartItem.service";
import { CartItemCreateInput } from "./CartItemCreateInput";
import { CartItem } from "./CartItem";
import { CartItemFindManyArgs } from "./CartItemFindManyArgs";
import { CartItemWhereUniqueInput } from "./CartItemWhereUniqueInput";
import { CartItemUpdateInput } from "./CartItemUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class CartItemControllerBase {
  constructor(protected readonly service: CartItemService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CartItem })
  async createCartItem(
    @common.Body() data: CartItemCreateInput
  ): Promise<CartItem> {
    return await this.service.createCartItem({
      data: {
        ...data,

        cart: data.cart
          ? {
              connect: data.cart,
            }
          : undefined,
      },
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CartItem] })
  @ApiNestedQuery(CartItemFindManyArgs)
  async cartItems(@common.Req() request: Request): Promise<CartItem[]> {
    const args = plainToClass(CartItemFindManyArgs, request.query);
    return this.service.cartItems({
      ...args,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CartItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cartItem(
    @common.Param() params: CartItemWhereUniqueInput
  ): Promise<CartItem | null> {
    const result = await this.service.cartItem({
      where: params,
      select: {
        cart: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CartItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCartItem(
    @common.Param() params: CartItemWhereUniqueInput,
    @common.Body() data: CartItemUpdateInput
  ): Promise<CartItem | null> {
    try {
      return await this.service.updateCartItem({
        where: params,
        data: {
          ...data,

          cart: data.cart
            ? {
                connect: data.cart,
              }
            : undefined,
        },
        select: {
          cart: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CartItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCartItem(
    @common.Param() params: CartItemWhereUniqueInput
  ): Promise<CartItem | null> {
    try {
      return await this.service.deleteCartItem({
        where: params,
        select: {
          cart: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: CartItemWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        brand: {
          select: {
            id: true,
          },
        },

        cartItem: {
          select: {
            id: true,
          },
        },

        category: {
          select: {
            id: true,
          },
        },

        colors: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,
        inStock: true,

        orderItem: {
          select: {
            id: true,
          },
        },

        price: true,
        sizes: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: CartItemWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateCartItem({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: CartItemWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateCartItem({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: CartItemWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateCartItem({
      where: params,
      data,
      select: { id: true },
    });
  }
}
