/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReturnRequestService } from "../returnRequest.service";
import { ReturnRequestCreateInput } from "./ReturnRequestCreateInput";
import { ReturnRequest } from "./ReturnRequest";
import { ReturnRequestFindManyArgs } from "./ReturnRequestFindManyArgs";
import { ReturnRequestWhereUniqueInput } from "./ReturnRequestWhereUniqueInput";
import { ReturnRequestUpdateInput } from "./ReturnRequestUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class ReturnRequestControllerBase {
  constructor(protected readonly service: ReturnRequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReturnRequest })
  async createReturnRequest(
    @common.Body() data: ReturnRequestCreateInput
  ): Promise<ReturnRequest> {
    return await this.service.createReturnRequest({
      data: {
        ...data,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        reason: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ReturnRequest] })
  @ApiNestedQuery(ReturnRequestFindManyArgs)
  async returnRequests(
    @common.Req() request: Request
  ): Promise<ReturnRequest[]> {
    const args = plainToClass(ReturnRequestFindManyArgs, request.query);
    return this.service.returnRequests({
      ...args,
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        reason: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReturnRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async returnRequest(
    @common.Param() params: ReturnRequestWhereUniqueInput
  ): Promise<ReturnRequest | null> {
    const result = await this.service.returnRequest({
      where: params,
      select: {
        createdAt: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        reason: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReturnRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateReturnRequest(
    @common.Param() params: ReturnRequestWhereUniqueInput,
    @common.Body() data: ReturnRequestUpdateInput
  ): Promise<ReturnRequest | null> {
    try {
      return await this.service.updateReturnRequest({
        where: params,
        data: {
          ...data,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          order: {
            select: {
              id: true,
            },
          },

          reason: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReturnRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteReturnRequest(
    @common.Param() params: ReturnRequestWhereUniqueInput
  ): Promise<ReturnRequest | null> {
    try {
      return await this.service.deleteReturnRequest({
        where: params,
        select: {
          createdAt: true,
          id: true,

          order: {
            select: {
              id: true,
            },
          },

          reason: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: ReturnRequestWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        orderItem: {
          select: {
            id: true,
          },
        },

        payment: {
          select: {
            id: true,
          },
        },

        returnRequest: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: ReturnRequestWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateReturnRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: ReturnRequestWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateReturnRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: ReturnRequestWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateReturnRequest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
