/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { OrderItemWhereUniqueInput } from "../../orderItem/base/OrderItemWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";
import { PaymentCreateNestedManyWithoutOrdersInput } from "./PaymentCreateNestedManyWithoutOrdersInput";
import { ReturnRequestWhereUniqueInput } from "../../returnRequest/base/ReturnRequestWhereUniqueInput";
import { ReturnRequestCreateNestedManyWithoutOrdersInput } from "./ReturnRequestCreateNestedManyWithoutOrdersInput";
import { UserCreateNestedManyWithoutOrdersInput } from "./UserCreateNestedManyWithoutOrdersInput";

@InputType()
class OrderCreateInput {
  @ApiProperty({
    required: false,
    type: () => OrderItemWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderItemWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderItemWhereUniqueInput, {
    nullable: true,
  })
  orderItem?: OrderItemWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PaymentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PaymentWhereUniqueInput)
  @IsOptional()
  @Field(() => PaymentWhereUniqueInput, {
    nullable: true,
  })
  payment?: PaymentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutOrdersInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => ReturnRequestWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ReturnRequestWhereUniqueInput)
  @IsOptional()
  @Field(() => ReturnRequestWhereUniqueInput, {
    nullable: true,
  })
  returnRequest?: ReturnRequestWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReturnRequestCreateNestedManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => ReturnRequestCreateNestedManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => ReturnRequestCreateNestedManyWithoutOrdersInput, {
    nullable: true,
  })
  returnRequests?: ReturnRequestCreateNestedManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutOrdersInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutOrdersInput;
}

export { OrderCreateInput as OrderCreateInput };
